const GRAVITY_SCALE = 0.64
const SPEEDUP = Math.sqrt(GRAVITY_SCALE)

export const PHYSICS_DICE_CONFIG = {
  defaults: {
    diceSize: 0.76,
    mass: 1.7,
    gravity: 30 * GRAVITY_SCALE,
    friction: 0.74,
    restitution: 0.3,
    linearDamping: 0.16 * SPEEDUP,
    angularDamping: 0.35 * SPEEDUP,
    throwForce: 3.3 * SPEEDUP,
    simulationHz: 480,
    softCcdPrediction: 0.15,
    spawnLinearSpeed: 3 * SPEEDUP,
    spawnLiftSpeed: 2 * SPEEDUP,
    spawnAngularSpeed: 9 * SPEEDUP,
  },
  quality: {
    eco: { pixelRatio: 1, shadows: false, shadowSize: 0 },
    balanced: { pixelRatio: 1.5, shadows: true, shadowSize: 512 },
    high: { pixelRatio: 2, shadows: true, shadowSize: 1024 },
  },
  scene: {
    baseDiceSize: 0.76,
    colliderHalfRatio: 0.499,
    bowlDiceScale: 0.78,
    resultDiceScale: 1.35,
    resultGap: 0.12,
    selectionBorder: { offsetRatio: 0.045, widthRatio: 0.018, cornerRadiusRatio: 0.151 },
    camera: {
      simulationHalfWidth: 4.25,
      resultHalfWidth: 4.25,
      minHalfHeight: 3.35,
      maxHalfHeight: 4.6,
      minHalfWidth: 3.3,
    },
    tray: {
      halfSize: 2.9,
      rollingHalfWidth: 2.5,
      rollingMinZ: -2.5,
      rollingMaxZ: 1.35,
      entryApronMaxX: 5.5,
      resultRowZ: -0.6,
      slotZ: 2.28,
      separatorZ: 1.5,
    },
    keepSlots: {
      diceScale: 1.35,
      gapRatio: 0.12,
      borderOffsetRatio: 0.065,
      borderWidthRatio: 0.016,
      barDepth: 0.05,
      barGap: 0.09,
      moveDurationMs: 380,
    },
    bowl: {
      autoTiltMs: 2400,
      startX: 0,
      startZ: -0.6,
      pourX: 2.9,
      pourZ: -0.6,
      hoverY: 0.28,
      tiltDurationMs: 520,
      rotationPivotY: 0.72,
      tiltTravelX: 0.48,
      tiltTravelZ: 0,
      tiltLiftY: 0.05,
      spillPushDurationMs: 220,
      spillPushTravelX: 0,
      exitDurationMs: 520,
      exitTravelX: 3.2,
      exitLiftY: 0.62,
      tiltDegrees: 104,
      visualTiltDegrees: 104,
      tiltDirection: 1,
      shakeIntervalMs: 105 / SPEEDUP,
      shakeStrength: 1.3,
      shakeOffsetX: 0.13,
      shakeOffsetZ: 0.11,
      shakeYaw: 0.075,
      shakeFollowStrength: 0.055,
      shakeCenterStrength: 0.025 * SPEEDUP,
      shakeOrbitStrength: 0.075 * SPEEDUP,
      shakeKickHeight: 0.45,
      shakeKickAltitude: 0.55,
      shakeRandomImpulse: 0.06 * SPEEDUP,
      shakeTorqueImpulse: 0.18 * SPEEDUP,
      followDecayMs: 340,
      followMinIntensity: 0.04,
      followPulseFloor: 0.4,
      followPulseGain: 0.6,
      followPulseImpulse: 0.55 * SPEEDUP,
      followStartEnergy: 0.75,
      spawnBaseY: 0.58,
      spawnRangeY: 0.08,
      spawnRadius: 0.68,
      spawnJitter: 0.06,
      colliderBottomHalfHeight: 0.09,
      colliderBottomY: 0.11,
      colliderBottomRadius: 1.5,
      colliderWallHalfWidth: 0.41,
      colliderWallHalfDepth: 0.12,
      colliderWallHalfHeight: 0.96,
      colliderWallY: 1.06,
      colliderWallRadius: 1.63,
      colliderLidY: 1.94,
      colliderLidHalfHeight: 0.08,
      colliderLidRadius: 1.7,
      releaseTiltProgress: 0.55,
      containmentRadius: 1.5,
      spillDirectionX: -1,
      spillForceMultiplier: 1,
      spillMinimumSpeed: 1.4,
      spillRandomSpeed: 0.4,
      spillLiftSpeed: 0.55,
      spillFanSpeed: 0.7,
      spillRandomZ: 0.35,
      visual: {
        outerBottomY: 0.03,
        outerBottomRadius: 1.56,
        innerBottomY: 0.2,
        innerBottomRadius: 1.44,
        innerRimRadius: 1.63,
        outerRimRadius: 1.87,
        rimRadius: 1.75,
        rimTube: 0.12,
        rimY: 2.02,
        segments: 48,
      },
    },
    alignment: {
      durationMs: 900,
      lineUpEnd: 0.68,
      lift: 0.52,
    },
    settlement: {
      angularSpeed: 0.18 * SPEEDUP,
      linearSpeed: 0.13 * SPEEDUP,
      minRollDurationMs: 900 / SPEEDUP,
      stableFrames: 5,
      maxRollDurationMs: 900 + 2900 / SPEEDUP,
    },
    safety: { margin: 0.16, bounce: 0.35, penetrationTolerance: 0.025 },
  },
} as const
